### ISSUE TITLE
[공통] 스터디 생성시 401 오류

### ISSUE THREAD

**Issue by airman5573** [woowacourse-teams/2022-moamoa#148]
## 요약
1. localhost에서 login을 한다
2. moamoa.space로 redirect를 한다
3. moamoa.space에서 accessToken을 복사해 localhost에 넣는다(테스트를 위해)
4. localhost에서 스터디 생성을 한다(accessToken이 있기 때문에 접근 가능)
5. 401 response를 받는다

참고: 이 테스트는 3분 안에 처리 되었습니다.

**Comment by nan-noo** [comment]
해결된 이슈
