### ISSUE TITLE
[FE] 스터디 생성후 메인 페이지 이동시 카드가 잘 추가되었는지 확인

### ISSUE THREAD

**Issue by airman5573** [woowacourse-teams/2022-moamoa#149]
스터디 생성후 react-router-dom의 navigate를 사용해 메인 페이지로 이동하는데, 이때 useQuery가 새로 데이타를 요청 하는지 확인해 봐야 합니다.

주의
- 현재 새로운 스터디가 맨 끝에 있기 때문에, scroll을 내렸을때 추가 요청이 보내지면서 새로 생성된 스터디가 불러와집니다.
- 그래서 최신 정렬이 되었을때 다시 확인해 봐야 합니다.

**Comment by nan-noo** [comment]
확인 결과 처음에 잘 생성됨
