### ISSUE TITLE
[공통] 스터디 디테일 API 명세 수정 (createdAt -> createdDate)

### ISSUE THREAD

**Issue by airman5573** [woowacourse-teams/2022-moamoa#181]
## 요약
현재 review에서는 createDate를 사용하고 있기 때문에  
스터디 디테일 API명세도 createdDate로 바꾸는게 좋을것 같아요 :D

**Comment by sc0116** [comment]
아아 이 부분은 createdDate가 맞아요! 수정하겠습니다

**Comment by nan-noo** [comment]
또 totalResults -> totalCount로 바꾸면 좋을 것 같아요

**Comment by tco0427** [comment]
해당 내용 반영하였으므로 close 하겠습니다..!
