### ISSUE TITLE
[FE] main.js 용량 줄여보기!

### ISSUE THREAD

**Issue by tco0427** [woowacourse-teams/2022-moamoa#217]
## 요약

main.js 용량 줄여보기

## 세부 설명

구구 피드백 : main.js 용량이 커서 첫 페이지 로드가 느리기 때문에 main.js 용량을 줄여보자!

**Comment by nan-noo** [comment]
1. react-icons 모듈 제거: 15.2MB -> 2.6MB
2. 소스맵 설정 변경: 2.6MB -> 538KB

추가로 tree shaking과 code splitting을 적용할 예정
