### ISSUE TITLE
[공통] 내가 참여한 스터디 조회 오류

### ISSUE THREAD

**Issue by jaejae-yoo** [woowacourse-teams/2022-moamoa#221]
## 요약
- 새로 생성한 스터디가 내가 참여한 스터디에 바로 추가되지 않는 오류
- Tag가 null인 경우 오류
- studyIds가 empty인 경우 오류

**Comment by wilgur513** [comment]
SELECT DISTINCT study.id, study.title, study.study_status, study.current_member_count,
study.max_member_count, study.start_date, study.end_date
FROM study LEFT JOIN study_member ON study_member.study_id = study.id
WHERE study_member.member_id = :id OR study.owner_id = :id

로 sql 변경 필요
