### ISSUE TITLE
[발표] 발표 자료(PPT) 스타일 정리

### ISSUE THREAD

**Issue by tco0427** [woowacourse-teams/2022-moamoa#25]
## 요약

발표 자료 PPT 스타일을 정리한다.

## 세부 설명
- 모아모아 로고 & 테마 색을 사용해 PPT 템플릿을 만든다.
- 글씨체 : 나눔스퀘어 라운드

**Comment by nan-noo** [comment]
https://docs.google.com/presentation/d/1-GJ-k7SvbPa-v3oLgWlqlX0v1TW_v_JhF4aDLQ4q47o/edit?usp=sharing
