### ISSUE TITLE
[FE] 테마 개선

### ISSUE THREAD

**Issue by nan-noo** [woowacourse-teams/2022-moamoa#319]
## 요약
테마 관련 리팩토링
## 세부 설명
지금은 컬러만 테마로 관리하고 있는데, 폰트 사이즈, border radius 등 통일성 없이 관리되고 있다. 
https://tailwindcss.com/docs/theme
이 링크의 예시코드처럼 테마 개선이 필요하다.

**Comment by airman5573** [comment]
처리해 보자고!
