### ISSUE TITLE
[FE] esbuild대신 babel사용

### ISSUE THREAD

**Issue by airman5573** [woowacourse-teams/2022-moamoa#324]
## 요약
esbuild대신 확장성이 더 좋은 babel을 사용합니다.

### babel은 속도가 느리지 않나요?
맞습니다. 그래서 esbuild를 사용했었는데, webpack5의 persistent cache와 esbuild의 minimizer를 같이 쓰면 그래도 속도가 많이 개선 됩니다.
- esbuild : 1.24s
- babel : 1.7s

### 어떤 확장성이요?
babel을 사용하면 다양한 babel-plugin을 사용할 수 있습니다.  
예를들어서 emotion의 [@emotion/babel-plugin](https://emotion.sh/docs/@emotion/babel-plugin)을 사용할 수 있습니다.

### @emotion/babel-plugin 은 왜 필요한건가요?
이 플러그인 있으면 component를 selector로 사용할 수 있습니다.  
className을 지양하는 경우 유용한 기능입니다.

**Comment by nan-noo** [comment]
테스트 결과
- esbuild loader가 빌드 속도, 번들 파일 용량 면에서 30%정도 우세

결론
- esbuild loader를 사용하기로 결정
