### ISSUE TITLE
[BE] 부하 테스트 자료 조사 및 테스트

### ISSUE THREAD

**Issue by jaejae-yoo** [woowacourse-teams/2022-moamoa#349]
## 요약
- 톰캣 threads max, max connections, accept count 설정을 위해 필요한 부하 테스트 자료 조사 및 테스트 공유

## 세부 설명
- 부하 테스트 도구 자료 조사 및 비교

# 정리
서비스를 배포하기 전에 현재 시스템이 어느 정도의 부하를 견딜 수 있는지 사전에 테스트하여 확인해야 합니다.

- 부하: 실행할 수 없어 대기하고 있는 프로세스의 수

- 성능
    - Time: 서비스가 얼마나 빠른지
    - TPS: 일정 시간 동안 얼마나 많이 처리할 수 있는지
    - Users: 얼마나 많은 사람들이 동시에 사용할 수 있는지

### 성능 테스트의 종류
- 스트레스(STRESS) TEST
    - 시스템이 과부하 상태에서 어떻게 동작하는지 검사하는 테스트(비정상적으로 높은 부하)
    - 시스템의 오류를 확인하고, 어떻게 시스템이 정상적으로 복구되는지를 살펴보는 것이 목적
   
- 부하(LOAD) TEST
    - 임계치의 한계에 도달할 때까지 시스템에 부하를 꾸준히 증가시키며 진행하는 테스트
    - 서비스의 일반적인 트래픽과 예상되는 최대 트래픽 상황에서 성능이 어떤지 확인합니다. 

- SMOKE TEST
    - 시나리오대로 애플리케이션이 동작하는지 확인하는 테스트

### 부하 테스트 도구
- JMeter
    - 복잡하고 디테일한 부하테스트가 가능
    - 시나리오 기반 테스트가 가능
    -  java로 이루어진 오픈소스의 성능테스트 도구
    - 다양한 프로토콜을 지원(HTTP, HTTPS)
    - 러닝 커브가 높은 편이다.
- nGrinder
    - 스크립트 작성 방법에 대한 학습이 필요. Groovy 기반.
    - 시나리오 테스트가 불가능. TPS 측정이 중점.
    - 스크립트 수정으로 세밀한 성능 테스트 가능
    - 사용하기 쉬운 편이다.
- K6
   -  시나리오 기반 테스트가 가능
   - Javascript로 코드 작성
   - 동시 접속자 수, 요청 간격, 최대 처리량 등 부하 조정이 가능
   - 클라우드로 테스트시 50회 이전까지는 무료. CLI로 실행하면 무료.
- locust
    - 로컬환경에서 천명 이상의 유저 테스트가 가능   
    - python 스크립트 코드로 테스트

**Comment by tco0427** [comment]
이슈 close 처리 할게요~_~
