### ISSUE TITLE
[FE] 스터디 상세페이지 리뷰 버그 수정

### ISSUE THREAD

**Issue by airman5573** [woowacourse-teams/2022-moamoa#395]
## 요약
아직 확인은 못했지만, 버그가 있다고 합니다.  
확인후 수정하겠습니다!

-----

에러원인  
<img width="577" alt="sc_ 17" src="https://user-images.githubusercontent.com/68623798/194804674-fffcd548-8ee9-4a2f-8278-b82638e9ae53.png">

size가 없을때 기본값으로 8을 넣었다;;

**Comment by nan-noo** [comment]
공지사항, 게시판, 후기 페이지 뷰 사이즈를 넘어가면 안보이는 문제
