### ISSUE TITLE
[FE] 웹 접근성 개선 

### ISSUE THREAD

**Issue by jhy979** [woowacourse-teams/2022-moamoa#408]
## 요약
🙌 모아모아의 웹 접근성을 개선한다.

## 세부 설명
- [x] 캐러셀 버튼을 한 번씩 읽기
- [ ] 스터디 제목 검색 input 수정창이라고 읽음
- [x] FE,BE를 에프이, 비이나 프론트엔드 백엔드로 읽도록 하기
- [ ] 상세페이지의 이미지를 읽어주지 않음
- [ ] 모집인원 인피니트를 읽어주지 않음
- [x] 헤딩 순서 맞추기
- [x] 프로필 이미지 안내나 로그아웃 모달이 띄워졌음을 알려줘야함
- [ ] 스터디에서 이미지,제목,설명, 모집 여부를 한 문장으로 읽음 -> 구분해주면 좋을듯
- [ ] 스터디 상세에서 "아직 작성된 후기가 없습니다"를 바로 읽음
- [x] 태그 읽을때 "태그"를 앞에 붙여주면 좋을듯

**Comment by nan-noo** [comment]
감사합니다 :D 
더 발전한 모아모아 서비스를 기대해주세요~!!

**Comment by daaaayeah** [comment]
모아모아 최고 👽🚀
