### ISSUE TITLE
[FE] 스터디 아이디가 currentMember로 들어간다

### ISSUE THREAD

**Issue by airman5573** [woowacourse-teams/2022-moamoa#414]
## 요약
스터디 아이디가 currentMember로 들어갑니다.

**Comment by nan-noo** [comment]
https://github.com/woowacourse-teams/2022-moamoa/pull/415
https://github.com/woowacourse-teams/2022-moamoa/pull/411
https://github.com/woowacourse-teams/2022-moamoa/pull/409
