### ISSUE TITLE
[공통] QA - 전체적인 버그 수정

### ISSUE THREAD

**Issue by jaejae-yoo** [woowacourse-teams/2022-moamoa#419]
## 요약
- [x] 스터디 상세 페이지 overflow-x scroll 
- [x] 스터디 개설 preview overflow-y scroll
- [ ] 공지사항, 게시판, 후기 페이지 뷰 사이즈를 넘어가면 안보이는 문제
- [x] 스터디 신청 마감일이 스터디 종료 이후인 경우 에러 메시지
    - 스터디 생성 에러가 발생했습니다 -> 스터디 신청 마감일은 스터디 종료 이전이어야 합니다.
- [x] 누구든지 스터디 방에 들어갈 수 있도록 수정(단, 읽기만 가능)
- [x] 로그인 성공시 이전 페이지로 이동
- [x] 스터디 개설시 subject tag 한 개 이상 선택하지 않으면 생성되지 않도록 수정

📌 추가적인 버그 발견시 추가해주세요.

**Comment by nan-noo** [comment]
공지사항, 게시판, 후기 페이지 뷰 사이즈를 넘어가면 안보이는 문제 -> @airman5573 PR에 포함될 예정입니다 :D 
나머지는 모두 수정했습니다.

**Comment by sc0116** [comment]
와 방금 후기 페이지 8개 이상이면 밀려서 보이는 버그 찾았는데 이미 찾은 버그구나 ㅎ
